#!/bin/bash
# Fetches LiteLLM pricing and generates EmbeddedPricing.swift
set -euo pipefail

URL="https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json"
OUT="Sources/CodexBarCore/Pipeline/EmbeddedPricing.swift"
TMP=$(mktemp)

echo "Fetching LiteLLM pricing..."
curl -sS --max-time 30 "$URL" -o "$TMP"

# Validate JSON
python3 -c "import json; json.load(open('$TMP'))" || { echo "Invalid JSON"; exit 1; }

# Get file size
SIZE=$(wc -c < "$TMP" | tr -d ' ')
echo "Downloaded ${SIZE} bytes"

# Generate Swift file
cat > "$OUT" << 'SWIFT_HEADER'
// Auto-generated by Scripts/update_embedded_pricing.sh — do not edit manually.
import Foundation

enum EmbeddedPricing {
    static let jsonData: Data = {
        Data(jsonString.utf8)
    }()

    // swiftlint:disable line_length
    private static let jsonString: String = ##"""
SWIFT_HEADER

cat "$TMP" >> "$OUT"

cat >> "$OUT" << 'SWIFT_FOOTER'
"""##
    // swiftlint:enable line_length
}
SWIFT_FOOTER

rm "$TMP"
echo "Generated $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
